This is a testharness.js-based test.
FAIL history pushState SECURITY_ERR assert_throws: function "function () {
        window.history.pushState(1, documen..." did not throw
Harness: the test ran to completion.

